### ISSUE TITLE
On windows this depends on regex.h and stdbool.h which cmake doesn't find.  Any suggestions?

### ISSUE THREAD

**Issue by johnweldon** [danielwaterworth/Raphters#1]
On windows this depends on regex.h and stdbool.h which cmake doesn't find.  Any suggestions?

**Comment by danielwaterworth** [comment]
It may be possible to compile using cygwin.

**Comment by johnweldon** [comment]
Thanks Daniel... I'll let you know if I find an MSVC solution.

**Comment by ghost** [comment]
stdbool.h is a standard C header. Should come with any modern compiler.

regex.h is a posix header.

**Comment by johnweldon** [comment]
I'm tired of seeing this.
