### ISSUE TITLE
Mac OS compilation issue

### ISSUE THREAD

**Issue by michaelachrisco** [danielwaterworth/Raphters#4]
I tried to compile the project using the xcode gcc and got the following error:

gcc simple.c -o test
Undefined symbols:
  "_response_empty", referenced from:
      _simple_func in cc6LuPel.o
      _default_handler_func in cc6LuPel.o
  "_response_add_header", referenced from:
      _simple_func in cc6LuPel.o
      _default_handler_func in cc6LuPel.o
  "_response_send", referenced from:
      _simple_func in cc6LuPel.o
      _default_handler_func in cc6LuPel.o
  "_add_handler", referenced from:
      _main in cc6LuPel.o
      _main in cc6LuPel.o
  "_response_write", referenced from:
      _simple_func in cc6LuPel.o
      _default_handler_func in cc6LuPel.o
  "_serve_forever", referenced from:
      _main in cc6LuPel.o
ld: symbol(s) not found
collect2: ld returned 1 exit status

**Comment by michaelachrisco** [comment]
One should note that I put sample.c on the root folder of the project.

**Comment by danielwaterworth** [comment]
Are you building using cmake?

**Comment by danielwaterworth** [comment]
I think you getting linker errors because you are only compiling simple.c, you need to compile the rest of the sources too.

**Comment by michaelachrisco** [comment]
Ohhh ok using cmake? Ill look into it and give a follow up in a bit. Thanks.

**Comment by michaelachrisco** [comment]
Quick question: how to use cmake on this project? I apologize in advance but first time I have used cmake. 
I should state I am looking at the man page as well.

**Comment by michaelachrisco** [comment]
NVM I saw your documentation and made the sample.c work. D'oh!
